### ISSUE TITLE
Add suffix for exceptions

### ISSUE THREAD

**Issue by piotrooo** [opentracing/opentracing-php#104]
In almost all languages (it's some kind of best practice I think), exceptions has suffix `Exception`. 
Furthermore, in PHP, built-in exceptions also has that suffix.

Should we implement it?

**Comment by jcchavezs** [comment]
I think that is more like a usual practice rather than a best practice. I don't see it adding too much value to the code. Could you maybe provide more info on the benefits of doing so?

**Comment by piotrooo** [comment]
In every libray or project I have been involved into, there was this suffix used. This allow fast reach a context and make less confusion 'what exactly this class is - an exception or not'.
As I said everybody (?) use this suffix, so maybe we can follow this standards?

**Comment by jcchavezs** [comment]
Agree on this. Could you please open a PR for this?
