### ISSUE TITLE
undefined method OpenTracing\SpanContext::createAsDefault()

### ISSUE THREAD

**Issue by jukylin** [opentracing/opentracing-php#17]
Hey !
    I found has not method "createAsDefault",in src\OpenTracing\NoopTracer.php #34.

```php
public function extract($format, Reader $carrier)
{
    return SpanContext::createAsDefault();
 }
```
It's 
```php
public function extract($format, Reader $carrier)
{
    return NoopSpanContext::create() ;
}
```
right ?

**Comment by jcchavezs** [comment]
Nice catch @jukylin! I just fixed it. This might never happen with tests but I am not sure if it is worth to test noop implementations for now.

**Comment by jukylin** [comment]
I creating [jaeger-php](https://github.com/jukylin/jaeger-php) and use noopTrace. so I foud that.
