### ISSUE TITLE
Change format values from `int` to `string`.

### ISSUE THREAD

**Issue by jcchavezs** [opentracing/opentracing-php#24]
[Using integer as formats](https://github.com/opentracing/opentracing-php/blob/9d90ea5fb1b0980670ece4a0a3affacebb4d6691/src/OpenTracing/Tracer.php#L16) does not scale as they don't identify formats properly, we would rather use descriptive, non-very-repeatable formats like in [Python](https://github.com/opentracing/opentracing-python/blob/b1595973c80babed5701e2849b842170fd5d85f4/opentracing/propagation.py#L61)

Ping @yurishkuro @felixfbecker @beberlei

**Comment by yurishkuro** [comment]
sgtm
