### ISSUE TITLE
Support tags injection via JAEGER_TAGS environment variable

### ISSUE THREAD

**Issue by otisg** [opentracing/opentracing-php#26]
For the sake of consistency, it would be useful if tags could be aggregated via JAEGER_TAGS environment variable like in the Java and, as of recently, Python clients.

**Comment by pavolloffay** [comment]
`JAEGER_TAGS` are jaeger specific. This is a vendor neutral API. 

I am not aware of any OT API that supports tracer level tags. Maybe it's better to discuss it on the specification repo.

For the people who don't know what are JAEGER_TAGS https://github.com/uber/jaeger-client-java/tree/master/jaeger-core

**Comment by jcchavezs** [comment]
I think it is pretty clear that this is not something we could include in the OpenTracing library. Thanks @otisg for taking the time to proposing this issue, I encourage you to keep looking at this repository.
