### ISSUE TITLE
missed implementation for php

### ISSUE THREAD

**Issue by ixpress** [opentracing/opentracing-php#29]
While, where is the "use AnOpenTracingImplementation\MyTracer;"?
Is there any OpenTracing Implementation for php?

**Comment by jcchavezs** [comment]
So OpenTracing library is a set of interfaces but when using it you actually want to use an concrete implementation (e.g. zipkin or datadog) that is the intention of this `AnOpenTracingImplementation`.

**Comment by beberlei** [comment]
The first task was getting the API finished, the next will be actual tracing implementations.

**Comment by jcchavezs** [comment]
I am closing this issue for now but as of some people is working in OT implementations we me might come up with a list soon.
