### ISSUE TITLE
Create CONTRIBUTING guidelines

### ISSUE THREAD

**Issue by jcchavezs** [opentracing/opentracing-php#35]

**Comment by piotrooo** [comment]
We can start with this from the very simple guide, afterwards try to enhance it.

First iteration of this document could looks.

Sections:

* Bugs report
* Features
* Coding style

**Comment by jcchavezs** [comment]
Sounds good. Worth to look at other languages and see what they provide.

tor. 18. apr. 2019, 20:37 skrev Piotr Olaszewski <notifications@github.com>:

**Comment by cawolf** [comment]
Could [this example from Dcotrine](https://github.com/portphp/doctrine/blob/master/CONTRIBUTING.md) be a starting point? And add the license part from [opentracing-java](https://github.com/opentracing/opentracing-java/blob/master/CONTRIBUTING.md)?

**Comment by jcchavezs** [comment]
I think both will work :). Would you open a PR for that @cawolf ?

**Comment by cawolf** [comment]
Done :)

**Comment by cawolf** [comment]
Relates to #93
