### ISSUE TITLE
Rename Ext to Tags

### ISSUE THREAD

**Issue by yurishkuro** [opentracing/opentracing-php#39]
I think it was a mistake in Go when we defined the standard tags in the `ext` package, it should've been called `tags`. My advise is to not repeat that mistake here.

Similarly, there can be a `logs` package for standard log fields.

**Comment by lvht** [comment]
Hi @yurishkuro , all the tags are just ** Conventions**. They are recommend, not limit. Actually, the value of these tags does not matter at all. Choose a different has no influence on you code to interact with different implementations.

So put them in the `Ext` package really make sense.

**Comment by jcchavezs** [comment]
Closed by https://github.com/opentracing/opentracing-php/pull/47
