### ISSUE TITLE
Create a Mock tracer implementation

### ISSUE THREAD

**Issue by yurishkuro** [opentracing/opentracing-php#40]
Most other language implementations support a Mock tracer. Having a mock tracer is useful for two reasons:
  * it allows unit testing of the instrumentation with only the opentracing dependency
  * implementing a mock tracer helps with ironing out the issues in the API itself, like #38, as it serves as a reference implementation

**Comment by jcchavezs** [comment]
Great feedback @yurishkuro however there is already an issue for this: https://github.com/opentracing/opentracing-php/issues/21

**Comment by yurishkuro** [comment]
sorry, should've checked the issues
