### ISSUE TITLE
Should we remove SpanContextNotFound?

### ISSUE THREAD

**Issue by jcchavezs** [opentracing/opentracing-php#49]
## Problem
After doing a couple implementation of OpenTracing, I did not have the necessity of using the `SpanContextNotFound` exception. More over, the flow when using this exception is cumbersome:

```php
try {
    $context = $tracer->extract(...);
} catch(Exception $e) {
    $context = SpanContext::createAsRoot();
}
```

whereas returning a null would be:

```php
$context = $tracer->extract(...);

if ($context === null) {
    ... // build root context
}
```

Finally, the `SpanContextNotFound` does not add additional value to the failure, so returning a `null` is good enough.

## Proposal
Get rid of the exception and return `null` in such cases.

Ping @tedsuo @yurishkuro @beberlei @felixfbecker @lvht

**Comment by yurishkuro** [comment]
+1, especially if childOf() can accept null, then you don't even need the null check.
