### ISSUE TITLE
What's the benefit of isTypeReferenceFrom() over instanceof ReferenceFrom?

### ISSUE THREAD

**Issue by felixfbecker** [opentracing/opentracing-php#5]
_From @felixfbecker on June 9, 2017 16:59_

If more types are added in the future, this puts a burden on us to always add type checking methods for them

_Copied from original issue: jcchavezs/opentracing-php#7_

**Comment by felixfbecker** [comment]
_From @jcchavezs on July 4, 2017 7:59_

@felixfbecker I'd avoid using `typeof` as I believe it is much better to ask questions to the object about its type rather than bypassing its knowledge by using `typeof`. In addition, that would make impossible to compose the reference classes for references. I'd rather leave the Reference as an interface and let the implementor to use composition or whatever other pattern making sure the contract is fulfilled and that it is the object itself the one answering questions about its type.

**Comment by jcchavezs** [comment]
Closed by https://github.com/opentracing/opentracing-php/pull/9
