### ISSUE TITLE
update license to Apache 2.0

### ISSUE THREAD

**Issue by eirinikos** [opentracing/opentracing-php#58]
## Background
Hello! There has been a discussion in opentracing/specification#61 in regards to having all OT projects be licensed as Apache 2.0.

Since OT is a CNCF project and all other CNCF projects have the Apache 2.0 license, we would like to update **opentracing-php** licensing accordingly.

## Problem
**opentracing-php** currently bears the MIT license.

## Proposal
Replace the contents of the LICENSE file with Apache 2.0 license text. Update README to reference the Apache license. (I have a commit ready with these changes.)

## Questions to address
We would like to give previous contributors a 7-day period to air any concerns or feedback.

(CC @dankohn @bhs)

**Comment by bhs** [comment]
cc @jcchavezs @tedsuo

**Comment by piotrooo** [comment]
Already done.

**Comment by zzarbi** [comment]
Can some close this issue then ?

**Comment by piotrooo** [comment]
ping @jcchavezs

**Comment by jcchavezs** [comment]
Done

José Carlos Chávez


ons. 15. mai 2019 kl. 06:01 skrev Piotr Olaszewski <notifications@github.com
