### ISSUE TITLE
Adds $closeSpanOnFinish as second parameter for activate

### ISSUE THREAD

**Issue by jcchavezs** [opentracing/opentracing-php#60]
## Background
`Tracer::startActiveSpan` starts and span that is captured in a `scope` and one of the `SpanOptions` allows you to determine whether the `Scope` will be closed when finishing the span by passing `['close_span_on_finish' => true]`.

## Problem
For usability matters, `$closeSpanOnFinish` should allow you to be passed when doing `ScopeManager::activate`. Those cases occur when starting an `Span` not as an active one and in such a case it is **impossible** to pass a value for `close_span_on_finish`.

## Proposal
Changes `ScopeManager::activate(OpenTracingSpan $span)` into `ScopeManager::activate(OpenTracingSpan $span, $closeSpanOnFinish)` so you can also decide to pass the `$closeSpanOnFinish` when activating a span in a `Scope`.

Java already does this: https://github.com/opentracing/opentracing-java/blob/master/opentracing-api/src/main/java/io/opentracing/ScopeManager.java#L36

Ping @yurishkuro @tedsuo @beberlei @ellisv

**Comment by jcchavezs** [comment]
Ping @eligijusvitkauskas-home24 @avsej @felixfbecker

**Comment by ellisv** [comment]
:+1:

But to add to this because of https://github.com/opentracing/opentracing-php/commit/3010347c7329578653546c0f4319ef34ed16aa84 commit we have inverted so that Span finish is able to close Scope. But current option name is misleading. Spans we finish, Scopes we close. So an option should be named something like `close_scope_on_finish`.

**Comment by jcchavezs** [comment]
@ellisv @yurishkuro I opened a PR to address this issue: https://github.com/opentracing/opentracing-php/pull/61/files

**Comment by jcchavezs** [comment]
Closed by https://github.com/opentracing/opentracing-php/pull/61
