### ISSUE TITLE
Should this package follow PSR naming convention?

### ISSUE THREAD

**Issue by ellisv** [opentracing/opentracing-php#69]
Doc: https://www.php-fig.org/bylaws/psr-naming-conventions/

It is common in PHP community to append `Interface` to the name when naming interfaces. Examples from various famous packages:
* https://github.com/php-fig/log/blob/master/Psr/Log/LoggerInterface.php
* https://github.com/php-fig/http-message/blob/master/src/MessageInterface.php
* https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/KernelInterface.php
* https://github.com/zendframework/zend-http/blob/master/src/Header/HeaderInterface.php

**Comment by jcchavezs** [comment]
I don't see any benefit on doing so. Using namespaces solves any sort of duplication issue naming we might have.

**Comment by fox91** [comment]
In my opinion, yes, the code is clearer and avoids misunderstanding.
Personally I use this convention in all my projects.

**Comment by piotrooo** [comment]
This looks like completed issue.

**Comment by cawolf** [comment]
@jcchavezs can you close this issue?

**Comment by fox91** [comment]
If I have not missed anything, it seems that the code has not been changed but the issue has been closed.
Can you add the label "wontfix" to this issue?

**Comment by jcchavezs** [comment]
Totally @fox91. Thanks!
