### ISSUE TITLE
Need support for php 5.6?

### ISSUE THREAD

**Issue by fox91** [opentracing/opentracing-php#74]
Numerous updated versions of the frameworks are removing support for earlier versions of PHP.

The most up-to-date frameworks (eg. Zend Expressive, etc.) only support PHP `^ 7.1`.

Is there a real need to still support PHP 5.6?

How many people will support OpenTracing support in a legacy PHP 5.6 based application instead of a new (or at least updated) one based on `^ 7.1`?

**Comment by vasseur-bax** [comment]
In my opinion limiting to ^7.1 would severely limit the usability of this library. It should support an as wide as possible/reasonable range of versions. It is up to implementers to set more strict limits. 

Actually, this library should be seen the same way as a PSR library. They use PHP >=5.3.0 and for good reason: to allow wide adoption of the standard.

I already had issues with this lib requiring at least 5.6, because our application and our third party's implementation of OpenTracing requires 5.5.

**Comment by jcchavezs** [comment]
@vasseur-bax if you need 5.5 compatibility you can open a PR for that. I
don't think we use too much 5.6 features.

José Carlos Chávez


Den tor. 8. nov. 2018 kl. 12:32 skrev vasseur-bax <notifications@github.com

**Comment by fox91** [comment]
> Actually, this library should be seen the same way as a PSR library. They use PHP >=5.3.0 and for good reason: to allow wide adoption of the standard.

Newest PSR library (`http-client` and `http-factory`) only support PHP >= 7.0!

PHP versions before 5.6 are deprecated (I talk about the support, not how many developers are actually using it).
Version 5.6 will be deprecated on 31 December 2018.
Version 7.0 will be deprecated on 03 December 2018.

https://en.wikipedia.org/wiki/PHP#Release_history

**Comment by jcchavezs** [comment]
Well, distributed tracing is aim to be used also in monoliths being splited
and I think keeping 5.6 for a year or so might help them with that. Once
the API is stable nothing is stopping us to write a PHP 7.0 version and cut
v2 of the library (not the spec).

José Carlos Chávez


Den tor. 8. nov. 2018 kl. 12:46 skrev Andrea Falco <notifications@github.com

**Comment by piotrooo** [comment]
Hello,

thanks for a good work with develop this project!

Look at the supported PHP versions: http://php.net/supported-versions.php

Currently 7.1 is in the Security Support period. I don't know how you want to maintain this project, but I suggest to make branch with support for versions < 7.1, and make master for >= 7.1 versions.
This allow you to backporting fixes into branch, and maintain the latest PHP version in the master.

**Comment by piotrooo** [comment]
@jcchavezs this issue can be close.

**Comment by sergeyklay** [comment]
BTW, there is closing issues using keywords which you could use in your pull request: 
https://help.github.com/en/articles/closing-issues-using-keywords

**Comment by piotrooo** [comment]
Thanks, good to know.

**Comment by jcchavezs** [comment]
https://github.com/opentracing/opentracing-php/pull/89
