### ISSUE TITLE
SpanBuilder interface

### ISSUE THREAD

**Issue by piotrooo** [opentracing/opentracing-php#80]
## Background
Missing SpanBuilder interface as like in the opentracing-java implementation. https://github.com/opentracing/opentracing-java/blob/3e78ba6126519053918ddae9fb8782b239c33bf7/opentracing-api/src/main/java/io/opentracing/Tracer.java#L109

## Problem
Missing SpanBuilder interface.

## Proposal
To make API more compatible with other languages implementations I suggest to introduce SpanBuilder interface.

## Questions to address
In PHP there is no thing like a internal interface, show how this should be implemented, as a new separated interface?

**Comment by jcchavezs** [comment]
@piotrooo thanks for coming by. I'd like to ask you to explain more about the actual **Problem** (explaining why this is needed). Regarding the *more compatibility with other language implementations* I am not entirely sure on that as I checked OT-ruby, OT-python and OT-go and none of them include such an interface.
That said, it is worth mentioning that OT-PHP includes a [StartSpanOptions](https://github.com/opentracing/opentracing-php/blob/master/src/OpenTracing/StartSpanOptions.php) for creation pattern.

**Comment by piotrooo** [comment]
I think a fluent builder can be more handy in use. 
E.g:
Now if you want to add more tags:

```
$span->setTag('key1', 'value1');
$span->setTag('key2', 'value2');
//etc...
```
With fluent builder could be:

```
$spanBuilder
    ->withTag('key1', 'value1')
    ->withTag('key2', 'value2');
//etc..
```

Consider following:

```
$scope = $tracer->startActiveSpan('something', ['child_of' => $spanContext]);
$scope->getSpan()->setTag('key1', 'value1');
$scope->getSpan()->setTag('key2', 'value2');
```

and compare it with:

```
$tracer->buildSpan('something')
    ->asChildOf($spanContext)
    ->withTag('key1', 'value1')
    ->withTag('key2', 'value2')
    ->startActive($finishSpanOnClose);
```

That is IMHO more elegant way to handle that case.

**Comment by jcchavezs** [comment]
Actually you can achieve this:
```php
$scope = $tracer->startActiveSpan('something', [
    'child_of' => $spanContext,
    'tags' => [
        'key' => 'value',
    ]
]);
```

**Comment by piotrooo** [comment]
Ahh, don't know about this, thanks.

But that way IMO is not OOP approach - as always in PHP arrays...
