### ISSUE TITLE
Type hinting

### ISSUE THREAD

**Issue by piotrooo** [opentracing/opentracing-php#88]
Hi,
now we have on our master branch PHP >= 7.1, maybe next step is use type hinting?

I have been done with some changes, almost all classes covered that changes. What do you think about it?

**Comment by jcchavezs** [comment]
I think this is the next natural step. A PR for this is welcome.

**Comment by sergeyklay** [comment]
@jcchavezs Consider to create a tag before merging to upstream

**Comment by Reasno** [comment]
A friendly reminder, this is a breaking change.

**Comment by jcchavezs** [comment]
Hi @reasno, truth is PHP 5.6 is long deprecated and we are moving the compatibility to PHP 7.2 to take advantages of typing in PHP and reduce the boiler plate in implementations.

**Comment by Reasno** [comment]
> Hi @Reasno, truth is PHP 5.6 is long deprecated and we are moving the compatibility to PHP 7.2 to take advantages of typing in PHP and reduce the boiler plate in implementations.

I am looking forward to it. Hope OT implemetations can keep up the pace.
