### ISSUE TITLE
Noop repackage

### ISSUE THREAD

**Issue by piotrooo** [opentracing/opentracing-php#90]
After reading a [specification](https://github.com/opentracing/specification/blob/master/specification.md#nooptracer) I was discovered a following sentence.

> In some cases (for example, Java) the NoopTracer may be in its own packaging artifact.

So maybe we should repackage a Noop related classes to the new package called `Noop` (like a mocks).

This will allow us to better organize classes, without mixing contents.

**Comment by jcchavezs** [comment]
Mixed feelings here. I tried this before (along with a new package for
Mock) but we decided to keep it as it is. If have time I will check the
original discussion when back from holidays.

fre. 19. apr. 2019, 06:57 skrev Piotr Olaszewski <notifications@github.com>:

**Comment by jcchavezs** [comment]
Check this discussion: https://github.com/opentracing/opentracing-php/pull/46#issuecomment-362558775

**Comment by piotrooo** [comment]
@jcchavezs how Noop* classes are related with the Mock* classes? And how repackage of that Noop* classes can interfere with whole codebase?

**Comment by jcchavezs** [comment]
They are different but the argument was the same.
