### ISSUE TITLE
Migrate Interfaces to use PHP 7.1

### ISSUE THREAD

**Issue by jcchavezs** [opentracing/opentracing-php#94]
## Background
Since PHP 5.6 and 7.0 are not supported anylonger, it makes sense to update the library.

Related to https://github.com/opentracing/opentracing-php/issues/74

Ping @cawolf

**Comment by piotrooo** [comment]
PHP 7.1 is also not supported (https://www.php.net/supported-versions.php), we should start from 7.2.

**Comment by cawolf** [comment]
I will start migrating to 7.1 level. The only big difference to 7.2 will be the added `object` type, and the composer dependency, of course.

In the meantime, you can discuss the actual point: whether to migrate to 7.2 directly.

**Comment by piotrooo** [comment]
Starting with unsupported and legacy version is not good in my opinion.

**Comment by cawolf** [comment]
Besides: I found only 1 file (`OpenTracing\Reference`), which missed a single return type hint. All interfaces are up-to-date according to both 7.1 and 7.2 specifications.

@jcchavezs , what am I missing?

**Comment by jcchavezs** [comment]
I think moving to 7.1 is good enough for now as it does not drag us to do retrocompatibility stuff like we did for PHP 5.6. Let's keep in mind that we should ease the migration for the implementations.

**Comment by cawolf** [comment]
> Besides: I found only 1 file (`OpenTracing\Reference`), which missed a single return type hint. All interfaces are up-to-date according to both 7.1 and 7.2 specifications.
> 
> @jcchavezs , what am I missing?

ping @jcchavezs :)

**Comment by jcchavezs** [comment]
@cawolf I would say the best way to make sure we are not missing types is including phpstan checks. Are you up to that? For a reference you can see https://github.com/openzipkin/zipkin-php/blob/master/composer.json#L55

**Comment by cawolf** [comment]
Roger that :)

**Comment by cawolf** [comment]
related to #93
